palette = "catppuccin_mocha"

format = """
[ 󰏚 $sudo ](fg:#090c0c bg:subtext1)\
[]( fg:subtext1 bg:sea)\

$directory\

$character
"""
right_format="([](fg:surface0)$python[](fg:surface0))"

add_newline=false

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sea="#b0cbff"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#212736"
mantle = "#181825"
crust = "#11111b" 

[character]
success_symbol="[](fg:sea bg:green)[](fg:bold green)"
error_symbol="[](fg:sea bg:red)[](fg:bold red)"
format="$symbol "

[sudo]
style="fg:#090c0c bg:subtext1"
disabled=false
format='([$symbol]($style))'
symbol=''

[directory]
style = "fg:#090c0c bg:sea"
format = "[ $path ]($style)"
truncation_length = 2

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = ""
"Pictures" = ""
"Projects" = ""

[git_branch]
symbol = ""
format = '[ $symbol $branch ](fg:#769ff0 bold bg:base)'

[git_status]
modified='[M](fg:#f78e25 bg:mantle)'
untracked='[U](fg:#ff836e bg:mantle)'
staged='[S](fg:#9aff8f bg:mantle)'
deleted='[X](fg:#d60924 bg:mantle)'
format = '[( $ahead_behind )](fg:#ffffff bg:mantle)[( $all_status )](fg:#769ff0 bg:mantle)'

[git_metrics]
added_style = "fg:bold green  bg:mantle"
deleted_style = "fg:bold red  bg:mantle"
format = '[ ([+$added]($added_style)) ([-$deleted]($deleted_style)) ](bg:mantle)'
disabled=false

[git_state]
format='\($state( $progress_current/$progress_total)\)'

[nodejs]
symbol = ""
style = "bg:base"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:base)]($style)'

[rust]
symbol = ""
style = "bg:base"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:base)]($style)'

[golang]
symbol = ""
style = "bg:base"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:base)]($style)'

[fill]
symbol = ' '

[php]
symbol = ""
style = "bg:base"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:base)]($style)'

[python]
symbol = ""
style = "fg:blue bg:surface0"
format = '([ $symbol$virtualenv ]($style))'
python_binary = 'python3'



[cmd_duration]
show_milliseconds=true
min_time=500
disabled=false
style='bold fg:#767d99'
format='[\(($duration)\)]($style)'
