palette = "catppuccin_mocha"

format = """
[ 󰏚 $sudo ](fg:base bg:peach)\
[]( fg:peach bg:mantle)\

$directory\

$character
"""
right_format="([](fg:surface0)$python[](fg:surface0))"

add_newline=false

[palettes.catppuccin_mocha]
base = "black"
mantle = "black"
surface0 = "bright-black"
surface1 = "bright-black"
surface2 = "bright-black"
text = "white"
rosewater = "bright-yellow"
lavender = "bright-blue"
red = "red"
peach = "bright-red"
yellow = "yellow"
green = "green"
teal = "cyan"
blue = "blue"
mauve = "magenta"
flamingo = "bright-white"




[character]
success_symbol="[](fg:mantle bg:surface0)[](fg:surface0)"
error_symbol="[](fg:mantle bg:red)[](fg:bold red)"
format="$symbol "

[sudo]
style="fg:mantle bg:peach"
disabled=false
format='([$symbol]($style))'
symbol=''

[directory]
style = "fg:peach bg:mantle"
format = "[ $path ]($style)"
truncation_length = 2

[git_branch]
symbol = ""
format = '[ $symbol $branch ](fg:#769ff0 bold bg:base)'

[git_status]
modified='[M](fg:#f78e25 bg:mantle)'
untracked='[U](fg:#ff836e bg:mantle)'
staged='[S](fg:#9aff8f bg:mantle)'
deleted='[X](fg:#d60924 bg:mantle)'
format = '[( $ahead_behind )](fg:#ffffff bg:mantle)[( $all_status )](fg:#769ff0 bg:mantle)'

[git_metrics]
added_style = "fg:bold green  bg:mantle"
deleted_style = "fg:bold red  bg:mantle"
format = '[ ([+$added]($added_style)) ([-$deleted]($deleted_style)) ](bg:mantle)'
disabled=false

[git_state]
format='\($state( $progress_current/$progress_total)\)'

[nodejs]
symbol = ""
style = "bg:base"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:base)]($style)'

[rust]
symbol = ""
style = "bg:base"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:base)]($style)'

[golang]
symbol = ""
style = "bg:base"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:base)]($style)'

[fill]
symbol = ' '

[php]
symbol = ""
style = "bg:base"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:base)]($style)'

[python]
symbol = ""
style = "fg:blue bg:surface0"
format = '([ $symbol$virtualenv ]($style))'
python_binary = 'python3'


[cmd_duration]
show_milliseconds=true
min_time=500
disabled=false
style='bold fg:#767d99'
format='[\(($duration)\)]($style)'
